### ISSUE TITLE
Unable to add GoogleMap layer

### ISSUE THREAD

**Issue by jaspervdbijl** [octavm/v-leaflet-shramov-parent#1]
I get the following javascript error

Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened

Added 
@JavaScript("http://maps.google.com/maps/api/js?v=3.2&amp;sensor=false") to LGoogleLayer 

Google map layer does not render

**Comment by jaspervdbijl** [comment]
Thanks for the response
Should have picked that up from the test code

**Comment by mstahv** [comment]
I think this should be better covered by instructions in README.md and/or directory page.

**Comment by mstahv** [comment]
If you have a couple of minutes, maybe you could add an example from your project to the readme file and send me a pull request.

**Comment by jaspervdbijl** [comment]
I created two pull requests

second one relating to LGoogleLayer

The javadoc through me off a bit
- Example (without API key, for local testing)
  - @JavaScript("http://maps.google.com/maps/api/js?v=3.2&amp;sensor=false")

On Mon, Jan 12, 2015 at 2:56 PM, Matti Tahvonen notifications@github.com
wrote:

> If you have a couple of minutes, maybe you could add an example from your
> project to the readme file and send me a pull request.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mstahv/v-leaflet-shramov-parent/issues/1#issuecomment-69565662
> .

## 

regards

Jasper van der Bijl

**Comment by mstahv** [comment]
Perfect! Big thanks!
