### ISSUE TITLE
LGoogleLayer does not pass though the context menu (right click) event to LMap

### ISSUE THREAD

**Issue by chenli868** [octavm/v-leaflet-shramov-parent#9]
Hi,

When using v-Leaflet-sharmov-0.0.4 with v-leaflet-1.0.0-b3, I can't seems to get the right click event from the google map layer with the following code example:
https://gist.github.com/mstahv/fc97922bcccdf0704831
If I draw any leaflet shapes (e.g. LPolyline, LMarker) on top of google map, then I can get the right click event from clicking the shapes.

I can currently draw a big transparent polygon overlay the whole map to get the event. It would be nice if you can point to me where to fix.

Thanks,

Li

**Comment by mstahv** [comment]
This might be quite hard to tackle as the google map layer is handled by google maps js. If google maps js has a context menu hooks, then that might be possible to proxy back to Leaflet/V-Leaflet event.

**Comment by chenli868** [comment]
Thanks for the quick reply. Google map does have a right click event:
http://stackoverflow.com/questions/7905733/google-maps-api-3-get-coordinates-from-right-click
Do you think update Google.js in g-leaflet-shramov with the "rightclick" event would be a starting point?
Thanks

**Comment by mstahv** [comment]
Yep, that would be the first step. The you could try to use [contextMenuRpc from the AbstractLeafletLayerConnector super class](https://github.com/mstahv/v-leaflet/blob/master/src/main/java/org/vaadin/addon/leaflet/client/AbstractLeafletLayerConnector.java#L28).

**Comment by mstahv** [comment]
Apparently it was easier than I thought. @octavm already provided a fix for this. I didn't yet try this, but if somebody can verify it works, I guess we can close this right away?

**Comment by chenli868** [comment]
Yes, that's a quick fix, Thanks :). Will this fix be published on vaadin addons repository?
